hook:
  placeholderapi: true

tps-performance-observation-value: -1

fake-players:
  enabled: false

  count-fake-players-to-online-players: false

remove-gray-color-from-tab-in-spectator: false

ignore-vanished-players-in-online-players: false

count-vanished-staffs: true

hide-player-from-tab-when-afk: false

hide-players-from-tablist: false

per-world-player-list:
  enabled: false

  world-groups:
    example1:
    - exampleWorld
    - exampleAnotherWorld

    exampleGroup2:
    - exampleWorld2
    - exampleAnotherWorld2

placeholder-format:
  afk-status:
    enable: false

    show-in-right-or-left-side: true

    show-player-group: true

    format-yes: "&7 [AFK]&r "
    format-no: ""

    sort-last: false

  time:
    time-zone: "GMT0"

    use-system-zone: false

    time-format: "mm:HH"

    date-format: "dd/MM/yyyy"

  ping:
    enable: true
    formats:
    - "&a%ping% <= 200"
    - "&6%ping% >= 200"
    - "&c%ping% > 500"

  tps:
    enable: true

    formats:
    - '&a%tps% > 18.0'
    - '&6%tps% == 16.0'
    - '&c%tps% < 16.0'

    size: 2

  memory-bar:
    char: "|"
    size: 80
    colors:
      used: "&c"
      free: "&a"
      allocation: "&e"
      released: "&6"

change-prefix-suffix-in-tablist:
  enable: true

  refresh-interval: 4

  disabled-worlds:
    use-as-whitelist: false
    list:
    - myWorldWithUpper

  sync-plugins-groups-with-tablist: true

  hide-group-when-player-vanished: false

  assign-global-group-to-normal: false

  prefer-primary-vault-group: false

  followNameTagVisibility: false

tablist-object-type:

  type: ping

  refresh-interval: 3

  disabled-worlds:
  - testingWorld

  object-settings:
    health:
      restricted-players:
      - exampleplayer
      - players

    custom:
      value: "%level%"

check-update: true

download-updates: false

logconsole: true
